name: Android Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: YourUsername/kernel_oneplus_sm8250
          ref: meteoric
          path: kernel_source

      - name: Set up Clang Toolchain
        run: |
          mkdir -p toolchain
          cd toolchain
          wget https://github.com/ClangBuiltLinux/android-prebuilts-clang/releases/download/clang-r522817/clang-r522817.tar.gz
          tar -xzf clang-r522817.tar.gz
          rm clang-r522817.tar.gz
          echo "TOOLCHAIN=$(pwd)/clang-r522817/bin" >> $GITHUB_ENV

      - name: Clone KernelSU
        run: |
          cd kernel_source
          echo "📥 Fetching KernelSU..."
          rm -rf drivers/kernelsu
          git clone --depth=1 https://github.com/tiann/KernelSU.git drivers/kernelsu
          echo "✅ KernelSU cloned into drivers/kernelsu"

      - name: Build Kernel
        run: |
          cd kernel_source
          export PATH=$TOOLCHAIN:$PATH
          make ARCH=arm64 O=out vendor/meteoric_defconfig
          make -j$(nproc) ARCH=arm64 O=out \
            CC=clang \
            LD=ld.lld \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: Image
          path: kernel_source/out/arch/arm64/boot/Image
          
